/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg_creator;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import javax.swing.UIManager;
import javax.swing.border.MatteBorder;

/**
 *
 * @author baryl
 */
public class Your_hero extends javax.swing.JFrame {

    /**
     * Creates new form Your_hero
     */
    public Your_hero() {
        super("RPG Cretor");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSex = new javax.swing.ButtonGroup();
        tabbedPanel = new javax.swing.JTabbedPane();
        panelName = new javax.swing.JPanel();
        buttonPicture = new javax.swing.JButton();
        labelName = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        labelStory = new javax.swing.JLabel();
        labeSex = new javax.swing.JLabel();
        scrollStory = new javax.swing.JScrollPane();
        textStory = new javax.swing.JTextArea();
        buttonSexMale = new javax.swing.JRadioButton();
        buttonSexFemale = new javax.swing.JRadioButton("Female",true);
        textAddPicture = new javax.swing.JTextField();
        buttonAddPicture = new javax.swing.JButton();
        panelRace = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRace = new javax.swing.JList<>();
        labelRace = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoRaceText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        panelClass = new javax.swing.JPanel();
        panelStats = new javax.swing.JPanel();
        panelEquipment = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableWeapon = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableItems = new javax.swing.JTable();
        labelWeight = new javax.swing.JLabel();
        buttonCalculateWeight = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemSaveCharacter = new javax.swing.JMenuItem();
        menuItemLoadCharacter = new javax.swing.JMenuItem();
        menuOptions = new javax.swing.JMenu();

        buttonGroupSex.add(buttonSexMale);
        buttonGroupSex.add(buttonSexFemale);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(600, 515));
        setResizable(false);

        buttonPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg_creator/question.png"))); // NOI18N
        buttonPicture.setText("buttonPicture");

        labelName.setFont(new Font("TimesRoman", Font.BOLD, 15));
        labelName.setText("Name");

        textName.setFont(new Font("TimesRoman", Font.ITALIC, 15));
        textName.setText("Forgotten");

        labelStory.setFont(new Font("TimesRoman", Font.BOLD, 15));
        labelStory.setText("Story");

        labeSex.setFont(new Font("TimesRoman", Font.BOLD, 15));
        labeSex.setText("Sex");

        scrollStory.createVerticalScrollBar();

        textStory.setFont(new Font("TimesRoman", Font.ITALIC, 15));
        textStory.setColumns(20);
        textStory.setRows(5);
        textStory.setText("Does not remember ...");
        textStory.setLineWrap(true);
        textStory.setWrapStyleWord(true);
        scrollStory.setViewportView(textStory);

        buttonSexMale.setFont(new Font("TimesRoman", Font.PLAIN, 15));
        buttonSexMale.setText("Male");
        buttonSexMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSexMaleActionPerformed(evt);
            }
        });

        buttonSexFemale.setFont(new Font("TimesRoman", Font.PLAIN, 15));
        buttonSexFemale.setText("Female");
        buttonSexFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSexFemaleActionPerformed(evt);
            }
        });

        textAddPicture.setFont(new Font("TimesRoman", Font.ITALIC, 15));
        textAddPicture.setText("question.png");

        buttonAddPicture.setFont(new Font("TimesRoman", Font.BOLD, 15));
        buttonAddPicture.setText("Add picture");
        buttonAddPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPictureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNameLayout = new javax.swing.GroupLayout(panelName);
        panelName.setLayout(panelNameLayout);
        panelNameLayout.setHorizontalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStory)
                    .addComponent(scrollStory, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNameLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labeSex)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelNameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNameLayout.createSequentialGroup()
                                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonSexFemale)
                                    .addComponent(buttonSexMale)
                                    .addComponent(buttonAddPicture))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(buttonPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textAddPicture))))
                .addContainerGap())
        );
        panelNameLayout.setVerticalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labeSex))
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNameLayout.createSequentialGroup()
                        .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSexMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStory)
                            .addComponent(buttonSexFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollStory))
                    .addGroup(panelNameLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAddPicture))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAddPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );

        tabbedPanel.addTab("Name", panelName);

        listRace.setFont(new Font("TimesRoman", Font.ITALIC, 15));
        listRace.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Human", "Elf", "Orc", "Dwarf", "Nargl" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listRace.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRaceValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listRace);

        labelRace.setFont(new Font("TimesRoman", Font.BOLD, 15));
        labelRace.setText("Races");

        infoRaceText.setEditable(false);
        infoRaceText.setColumns(20);
        infoRaceText.setRows(5);
        infoRaceText.setFont(new Font("TimesRoman", Font.ITALIC, 15));
        infoRaceText.setLineWrap(true);
        infoRaceText.setWrapStyleWord(true);
        infoRaceText.setText("First select your race");
        jScrollPane2.setViewportView(infoRaceText);

        jLabel1.setFont(new Font("TimesRoman", Font.BOLD, 15));
        jLabel1.setText("Info");

        javax.swing.GroupLayout panelRaceLayout = new javax.swing.GroupLayout(panelRace);
        panelRace.setLayout(panelRaceLayout);
        panelRaceLayout.setHorizontalGroup(
            panelRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRace)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149)
                .addGroup(panelRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panelRaceLayout.setVerticalGroup(
            panelRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRace)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(panelRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Race", panelRace);
        panelRace.setBackground(Color.lightGray);

        javax.swing.GroupLayout panelClassLayout = new javax.swing.GroupLayout(panelClass);
        panelClass.setLayout(panelClassLayout);
        panelClassLayout.setHorizontalGroup(
            panelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        panelClassLayout.setVerticalGroup(
            panelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Class", panelClass);
        panelClass.setBackground(Color.lightGray);

        javax.swing.GroupLayout panelStatsLayout = new javax.swing.GroupLayout(panelStats);
        panelStats.setLayout(panelStatsLayout);
        panelStatsLayout.setHorizontalGroup(
            panelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        panelStatsLayout.setVerticalGroup(
            panelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Stats", panelStats);
        panelStats.setBackground(Color.lightGray);

        tableWeapon.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), javax.swing.BorderFactory.createCompoundBorder()));
        tableWeapon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Weapon", "Stats", "Range", "Weight", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableWeapon.setToolTipText("");
        tableWeapon.setAutoscrolls(false);
        jScrollPane3.setViewportView(tableWeapon);

        tableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Description", "Weight"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableItems);

        labelWeight.setText("0");

        buttonCalculateWeight.setText("Calculate Weight");
        buttonCalculateWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateWeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEquipmentLayout = new javax.swing.GroupLayout(panelEquipment);
        panelEquipment.setLayout(panelEquipmentLayout);
        panelEquipmentLayout.setHorizontalGroup(
            panelEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEquipmentLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWeight)
                            .addComponent(buttonCalculateWeight))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelEquipmentLayout.setVerticalGroup(
            panelEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipmentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEquipmentLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(buttonCalculateWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelWeight))
                    .addGroup(panelEquipmentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Equipment", panelEquipment);
        panelEquipment.setBackground(Color.lightGray);

        menuFile.setFont(new Font("TimesRoman", Font.BOLD, 15));
        menuFile.setText("File");

        menuItemSaveCharacter.setText("Save character");
        menuItemSaveCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveCharacterActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSaveCharacter);

        menuItemLoadCharacter.setText("Load Character");
        menuFile.add(menuItemLoadCharacter);

        menuBar.add(menuFile);

        menuOptions.setFont(new Font("TimesRoman", Font.BOLD, 15));
        menuOptions.setText("Options");
        menuBar.add(menuOptions);

        setJMenuBar(menuBar);
        menuBar.setFont(new Font("TimesRoman", Font.BOLD, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );

        tabbedPanel.setFont(new Font("TimesRoman", Font.BOLD, 15));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSaveCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveCharacterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSaveCharacterActionPerformed

    private void buttonSexFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSexFemaleActionPerformed
        try{
        buttonPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg_creator/women.jpg")));
        }
        catch(Exception e)
        {
            textAddPicture.setText("woman.jpg is missing");
        }
    }//GEN-LAST:event_buttonSexFemaleActionPerformed

    private void buttonSexMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSexMaleActionPerformed
        try{
        buttonPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg_creator/man.jpg")));
        }
        catch(Exception e)
        {
            textAddPicture.setText("man.jpg is missing");
        }
    }//GEN-LAST:event_buttonSexMaleActionPerformed

    private void buttonAddPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPictureActionPerformed
        try{
        buttonPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg_creator/"+textAddPicture.getText())));
        }
        catch(Exception e){
            textAddPicture.setText("There is no file of this name");
        }
    }//GEN-LAST:event_buttonAddPictureActionPerformed

    private void listRaceValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRaceValueChanged
        String selected=listRace.getSelectedValue();
        if(selected.equals("Human"))infoRaceText.setText("That is a average,"
                + " plain looking human");
        if(selected.equals("Elf"))infoRaceText.setText("Really we want alf in this??");
        if(selected.equals("Dwarf"))infoRaceText.setText("And whats next orcs");
        if(selected.equals("Orc"))infoRaceText.setText("Ohh for god sake");
        if(selected.equals("Nargl"))infoRaceText.setText("You just created this "
                + "and does not even know what it might look");
    }//GEN-LAST:event_listRaceValueChanged

    private void buttonCalculateWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateWeightActionPerformed
        Integer x=0;
        for(int i=0;i<4;i++)
        {
            if(tableWeapon.getModel().getValueAt(i,3)!=null)
            x+=(Integer)tableWeapon.getModel().getValueAt(i,3);
        }
        for(int i=0;i<20;i++)
        {
            if(tableItems.getModel().getValueAt(i,2)!=null)
            x+=(Integer)tableItems.getModel().getValueAt(i,2);
        }
        labelWeight.setText(Integer.toString(x));
    }//GEN-LAST:event_buttonCalculateWeightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Your_hero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Your_hero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Your_hero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Your_hero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Your_hero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddPicture;
    private javax.swing.JButton buttonCalculateWeight;
    private javax.swing.ButtonGroup buttonGroupSex;
    private javax.swing.JButton buttonPicture;
    private javax.swing.JRadioButton buttonSexFemale;
    private javax.swing.JRadioButton buttonSexMale;
    private javax.swing.JTextArea infoRaceText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labeSex;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelRace;
    private javax.swing.JLabel labelStory;
    private javax.swing.JLabel labelWeight;
    private javax.swing.JList<String> listRace;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemLoadCharacter;
    private javax.swing.JMenuItem menuItemSaveCharacter;
    private javax.swing.JMenu menuOptions;
    private javax.swing.JPanel panelClass;
    private javax.swing.JPanel panelEquipment;
    private javax.swing.JPanel panelName;
    private javax.swing.JPanel panelRace;
    private javax.swing.JPanel panelStats;
    private javax.swing.JScrollPane scrollStory;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTable tableItems;
    private javax.swing.JTable tableWeapon;
    private javax.swing.JTextField textAddPicture;
    private javax.swing.JTextField textName;
    private javax.swing.JTextArea textStory;
    // End of variables declaration//GEN-END:variables
}
