/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg_creator;

import java.awt.Color;
import java.awt.Font;
import java.io.File;

/**
 *
 * @author baryl
 */
public class Your_hero extends javax.swing.JFrame {

    /**
     * Creates new form Your_hero
     */
    public Your_hero() {
        super("RPG Cretor");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSex = new javax.swing.ButtonGroup();
        tabbedPanel = new javax.swing.JTabbedPane();
        panelName = new javax.swing.JPanel();
        buttonPicture = new javax.swing.JButton();
        labelName = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        labelStory = new javax.swing.JLabel();
        labeSex = new javax.swing.JLabel();
        scrollStory = new javax.swing.JScrollPane();
        textStory = new javax.swing.JTextArea();
        buttonSexMale = new javax.swing.JRadioButton();
        buttonSexFemale = new javax.swing.JRadioButton("Female",true);
        textAddPicture = new javax.swing.JTextField();
        buttonAddPicture = new javax.swing.JButton();
        panelRace = new javax.swing.JPanel();
        panelClass = new javax.swing.JPanel();
        panelStats = new javax.swing.JPanel();
        panelEquipment = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemSaveCharacter = new javax.swing.JMenuItem();
        menuItemLoadCharacter = new javax.swing.JMenuItem();
        menuOptions = new javax.swing.JMenu();

        buttonGroupSex.add(buttonSexMale);
        buttonGroupSex.add(buttonSexFemale);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg_creator/question.png"))); // NOI18N
        buttonPicture.setText("buttonPicture");

        labelName.setFont(new Font("TimesRoman", Font.BOLD, 15));
        labelName.setText("Name");

        textName.setFont(new Font("TimesRoman", Font.ITALIC, 15));
        textName.setText("Forgotten");

        labelStory.setFont(new Font("TimesRoman", Font.BOLD, 15));
        labelStory.setText("Story");

        labeSex.setFont(new Font("TimesRoman", Font.BOLD, 15));
        labeSex.setText("Sex");

        scrollStory.createVerticalScrollBar();

        textStory.setFont(new Font("TimesRoman", Font.ITALIC, 15));
        textStory.setColumns(20);
        textStory.setRows(5);
        textStory.setText("Does not remember ...");
        textStory.setLineWrap(true);
        textStory.setWrapStyleWord(true);
        scrollStory.setViewportView(textStory);

        buttonSexMale.setFont(new Font("TimesRoman", Font.PLAIN, 15));
        buttonSexMale.setText("Male");
        buttonSexMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSexMaleActionPerformed(evt);
            }
        });

        buttonSexFemale.setFont(new Font("TimesRoman", Font.PLAIN, 15));
        buttonSexFemale.setText("Female");
        buttonSexFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSexFemaleActionPerformed(evt);
            }
        });

        textAddPicture.setFont(new Font("TimesRoman", Font.ITALIC, 15));
        textAddPicture.setText("question.png");

        buttonAddPicture.setFont(new Font("TimesRoman", Font.BOLD, 15));
        buttonAddPicture.setText("Add picture");
        buttonAddPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPictureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNameLayout = new javax.swing.GroupLayout(panelName);
        panelName.setLayout(panelNameLayout);
        panelNameLayout.setHorizontalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStory)
                    .addComponent(scrollStory, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNameLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labeSex)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelNameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNameLayout.createSequentialGroup()
                                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonSexFemale)
                                    .addComponent(buttonSexMale)
                                    .addComponent(buttonAddPicture))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(buttonPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textAddPicture))))
                .addContainerGap())
        );
        panelNameLayout.setVerticalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(labeSex))
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNameLayout.createSequentialGroup()
                        .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSexMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStory)
                            .addComponent(buttonSexFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollStory))
                    .addGroup(panelNameLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAddPicture))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAddPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );

        tabbedPanel.addTab("Name", panelName);

        javax.swing.GroupLayout panelRaceLayout = new javax.swing.GroupLayout(panelRace);
        panelRace.setLayout(panelRaceLayout);
        panelRaceLayout.setHorizontalGroup(
            panelRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        panelRaceLayout.setVerticalGroup(
            panelRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Race", panelRace);
        panelRace.setBackground(Color.lightGray);

        javax.swing.GroupLayout panelClassLayout = new javax.swing.GroupLayout(panelClass);
        panelClass.setLayout(panelClassLayout);
        panelClassLayout.setHorizontalGroup(
            panelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        panelClassLayout.setVerticalGroup(
            panelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Class", panelClass);
        panelClass.setBackground(Color.lightGray);

        javax.swing.GroupLayout panelStatsLayout = new javax.swing.GroupLayout(panelStats);
        panelStats.setLayout(panelStatsLayout);
        panelStatsLayout.setHorizontalGroup(
            panelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        panelStatsLayout.setVerticalGroup(
            panelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Stats", panelStats);
        panelStats.setBackground(Color.lightGray);

        javax.swing.GroupLayout panelEquipmentLayout = new javax.swing.GroupLayout(panelEquipment);
        panelEquipment.setLayout(panelEquipmentLayout);
        panelEquipmentLayout.setHorizontalGroup(
            panelEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        panelEquipmentLayout.setVerticalGroup(
            panelEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Equipment", panelEquipment);
        panelEquipment.setBackground(Color.lightGray);

        menuFile.setFont(new Font("TimesRoman", Font.BOLD, 15));
        menuFile.setText("File");

        menuItemSaveCharacter.setText("Save character");
        menuItemSaveCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveCharacterActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSaveCharacter);

        menuItemLoadCharacter.setText("Load Character");
        menuFile.add(menuItemLoadCharacter);

        menuBar.add(menuFile);

        menuOptions.setFont(new Font("TimesRoman", Font.BOLD, 15));
        menuOptions.setText("Options");
        menuBar.add(menuOptions);

        setJMenuBar(menuBar);
        menuBar.setFont(new Font("TimesRoman", Font.BOLD, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );

        tabbedPanel.setFont(new Font("TimesRoman", Font.BOLD, 15));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSaveCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveCharacterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSaveCharacterActionPerformed

    private void buttonSexFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSexFemaleActionPerformed
        try{
        buttonPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg_creator/women.jpg")));
        }
        catch(Exception e)
        {
            textAddPicture.setText("woman.jpg is missing");
        }
    }//GEN-LAST:event_buttonSexFemaleActionPerformed

    private void buttonSexMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSexMaleActionPerformed
        try{
        buttonPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg_creator/man.jpg")));
        }
        catch(Exception e)
        {
            textAddPicture.setText("man.jpg is missing");
        }
    }//GEN-LAST:event_buttonSexMaleActionPerformed

    private void buttonAddPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPictureActionPerformed
        try{
        buttonPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg_creator/"+textAddPicture.getText())));
        }
        catch(Exception e){
            textAddPicture.setText("There is no file of this name");
        }
    }//GEN-LAST:event_buttonAddPictureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Your_hero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Your_hero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Your_hero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Your_hero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Your_hero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddPicture;
    private javax.swing.ButtonGroup buttonGroupSex;
    private javax.swing.JButton buttonPicture;
    private javax.swing.JRadioButton buttonSexFemale;
    private javax.swing.JRadioButton buttonSexMale;
    private javax.swing.JLabel labeSex;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelStory;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemLoadCharacter;
    private javax.swing.JMenuItem menuItemSaveCharacter;
    private javax.swing.JMenu menuOptions;
    private javax.swing.JPanel panelClass;
    private javax.swing.JPanel panelEquipment;
    private javax.swing.JPanel panelName;
    private javax.swing.JPanel panelRace;
    private javax.swing.JPanel panelStats;
    private javax.swing.JScrollPane scrollStory;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTextField textAddPicture;
    private javax.swing.JTextField textName;
    private javax.swing.JTextArea textStory;
    // End of variables declaration//GEN-END:variables
}
